server:
  port: 8084

spring:
  application:
    name: cities-service
  jpa:
    hibernate:
      ddl-auto: update
    database-plataform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/cities_service?useSSL=false&serverTimezone=UTC
    username: usercity
    password: userCity1978

eureka:
  client:
    service-url-defaultZone: eureka-server:8761/eureka


